name: Release

on:
  push:
    tags:
      - 'v*.*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [ Release ]
        cpp_compiler: [ cl ]
        c_compiler: [ cl ]
    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Copy EXE to artifact dir
        run: |
          mkdir -p artifact
          cp build/src/Release/TrayApp.exe artifact/ResoSwitch.exe

      - name: Get version from tag
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"
        shell: bash

      - name: Zip EXE
        run: |
          cd artifact
          7z a ../ResoSwitch-${{ steps.get_version.outputs.VERSION }}.zip ResoSwitch.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ResoSwitch-${{ steps.get_version.outputs.VERSION }}.zip
